services:
  frontend:
    container_name: school_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
