name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Clean up old frontend files (optional)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_FE }} << 'EOF'
            echo "Fixing permissions in frontend directory (if needed)..."
            sudo chown -R $USER:$USER ~/School-Management-System-Frontend || true
          EOF

      - name: Sync frontend code to EC2 (frontend server)
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_FE }}:~/School-Management-System-Frontend/

      - name: Deploy frontend on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_FE }} << 'EOF'
            set -e

            cd ~/School-Management-System-Frontend

            echo "Rebuilding and restarting frontend container..."
            docker compose up -d --build --force-recreate frontend

            echo "Cleaning up dangling images..."
            docker image prune -f --filter "dangling=true"
          EOF
