name: Build and Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # Change if frontend is on another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        run: |
          docker build -t school-frontend:latest .

      - name: Save image to tar file
        run: |
          docker save school-frontend:latest -o frontend.tar

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Transfer tar to EC2
        run: |
          scp -o StrictHostKeyChecking=no frontend.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_FE }}:/home/${{ secrets.EC2_USER }}/frontend.tar

      - name: Load and run image on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_FE }} << 'EOF'
            set -e

            echo "📦 Loading Docker image..."
            docker load -i frontend.tar

            echo "🛑 Stopping existing container..."
            docker stop school-frontend || true
            docker rm school-frontend || true

            echo "🚀 Running new container..."
            docker run -d --name school-frontend -p 80:80 --restart unless-stopped school-frontend:latest

            echo "🧹 Cleaning up..."
            rm frontend.tar
          EOF
