name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_FRONTEND_KEY }}

      - name: Fix permissions (optional, for non-root user)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_FE_USER }}@${{ secrets.EC2_FE_HOST }} \
            "sudo chown -R \$USER:\$USER ~/School-Frontend || true"

      - name: Sync frontend files to EC2
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_FE_USER }}@${{ secrets.EC2_FE_HOST }}:~/School-Frontend/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_FE_USER }}@${{ secrets.EC2_FE_HOST }} << 'EOF'
            set -e
            cd ~/School-Frontend
            docker compose down || true
            source /etc/environment
            docker compose up -d --build
            docker image prune -f
            docker container prune -f || true
          EOF
